[package]
name = "uplifttansen/adopt-me-player-scripts"
version = "0.0.1"
description = "https://github.com/UpliftTansen/adopt-me-player-scripts"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayerModule = "upliftgames/playermodule@569.2.5690484"