[package]
name = "upliftgames/adopt-me-playermodule"
version = "0.0.17"
registry = "https://github.com/UpliftGames/wally-internal-index"
realm = "shared"
exclude = ["test"]

[dependencies]
PlayerModule = "upliftgames/playermodule@578.0.5780566"